services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - mtu-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      - mtu-network

volumes:
  rabbitmq_data:
  redis_data:

networks:
  mtu-network:
    driver: bridge