name: Publish NuGet Package

on:
  push:
    tags:
      - '*.*.*'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build


  pack:
    name: Pack NuGet
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Pack
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          echo "Package version: $VERSION"

          dotnet pack ./mtueventbus/MtuEventBus.csproj \
            --configuration Release \
            --no-restore \
            -p:PackageVersion=$VERSION \
            -o ./packages

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: packages/*.nupkg


  publish:
    name: Publish to NuGet.org
    needs: pack
    runs-on: ubuntu-latest

    steps:
      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "packages/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate
